// Builds the sandboxed-iframe Excalidraw runtime and writes it, plus the offline fonts,
// into server/*.gen.ts. The daemon serves them over plugin RPC (see server/assets.ts).
// Run via `npm run build`; the manifest `build` step does this for Git installs.
import { build } from "esbuild";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";

if (process.argv.includes("--if-missing") && existsSync("server/runtime.gen.ts")) {
  process.exit(0);
}

const excalidrawDist = path.resolve("node_modules/@excalidraw/excalidraw/dist/prod");

// Excalidraw's CSS references its UI font by relative URL, which an offline iframe cannot fetch.
// Inline those files as data URIs.
const inlineCssFonts = {
  name: "inline-css-fonts",
  setup(b) {
    b.onLoad({ filter: /index\.css$/ }, (args) => {
      const css = readFileSync(args.path, "utf8").replace(
        /url\((["']?)(?:\.\/)?(fonts\/[^)"']+\.woff2)\1\)/g,
        (_match, _quote, file) =>
          `url(data:font/woff2;base64,${readFileSync(path.join(excalidrawDist, file)).toString("base64")})`,
      );
      return { contents: css, loader: "text" };
    });
  },
};

// The text-to-diagram dialog lazily imports Mermaid (~3 MB); it is not used here.
const stubMermaid = {
  name: "stub-mermaid",
  setup(b) {
    b.onResolve({ filter: /^(@excalidraw\/mermaid-to-excalidraw|mermaid)(\/|$)/ }, (args) => ({
      path: args.path,
      namespace: "stub-mermaid",
    }));
    b.onLoad({ filter: /.*/, namespace: "stub-mermaid" }, () => ({
      contents: "export default {}; export const parseMermaidToExcalidraw = async () => { throw new Error('Mermaid is not available'); };",
      loader: "js",
    }));
  },
};

// Only English is shipped; every other locale chunk is replaced by an empty module.
const stubLocales = {
  name: "stub-locales",
  setup(b) {
    b.onResolve({ filter: /(^|\/)locales\/[^/]+\.js$/ }, (args) =>
      /locales\/en[-.]/.test(args.path) ? undefined : { path: args.path, namespace: "stub-locale" },
    );
    b.onLoad({ filter: /.*/, namespace: "stub-locale" }, () => ({
      contents: "export default {};",
      loader: "js",
    }));
  },
};

const fonts = {};
const fontsDir = path.join(excalidrawDist, "fonts");
for (const family of readdirSync(fontsDir)) {
  if (family === "Xiaolai") continue; // 13 MB of CJK; falls back to system fonts
  for (const file of readdirSync(path.join(fontsDir, family))) {
    const full = path.join(fontsDir, family, file);
    if (statSync(full).isFile()) fonts[`fonts/${family}/${file}`] = readFileSync(full).toString("base64");
  }
}

writeFileSync(
  "runtime-src/fonts.gen.ts",
  `// Generated by scripts/build-runtime.mjs. Do not edit.\nexport const FONTS: Record<string, string> = ${JSON.stringify(fonts)};\n`,
);

const result = await build({
  entryPoints: ["runtime-src/main.tsx"],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: "es2020",
  jsx: "automatic",
  minify: true,
  legalComments: "none",
  conditions: ["production"],
  loader: { ".css": "text" },
  define: { "process.env.NODE_ENV": '"production"', "process.env.IS_PREACT": '"false"' },
  plugins: [inlineCssFonts, stubLocales, stubMermaid],
  logLevel: "warning",
});
const js = result.outputFiles[0].text.replaceAll("</script", "<\\/script");
// The frame never needs the network: scripts, fonts and images are all inline, data: or blob:.
const csp = [
  "default-src 'none'",
  "script-src 'unsafe-inline' blob:",
  "style-src 'unsafe-inline'",
  "font-src data: blob:",
  "img-src data: blob:",
  "connect-src data: blob:",
  "worker-src blob:",
].join("; ");
const html =
  `<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="${csp}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>` +
  '<body style="margin:0"><div id="root"></div><script>' +
  js +
  "</script></body></html>";

const header = "// Generated by scripts/build-runtime.mjs. Do not edit.\n";
writeFileSync("server/runtime.gen.ts", `${header}export const runtimeHtml: string = ${JSON.stringify(html)};\n`);
console.log(
  `runtime html ${(html.length / 1e6).toFixed(2)} MB, ${Object.keys(fonts).length} font files`,
);
